version: "0.0.0"
services:
  cultivator-backend:
    build: .
    ports:
      - "8123:8123"
    depends_on:
      - "postgres"
    command: sh -c "/wait && ./Cultivator"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
  postgres:
    image: "postgres:14.2-alpine"
    environment:
      - POSTGRES_USER=cultivator
      - POSTGRES_PASSWORD=drowssap
      - POSTGRES_DB=cultivator